export { default as CalendarLayout } from './CalendarLayout'
export { default as Contacto } from './Contacto'
export { default as EquiposLayout } from './EquiposLayout'
export { default as LayoutApp } from './LayoutApp'
export { default as PlayersLayout } from './PlayersLayout'
export { default as ReglamentoLayout } from './ReglamentoLayout'
export { default as StatsLayout } from './StatsLayout'
export * from './index'
